#This is the development branch CI that will run and deploy the frontend to the S3 dev bucket

name: Production Frontend CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop-b branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #  matrix:
    #    node-version: [14.17.5]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Use the node version specified in the strategy
      #- name: Use Node.js ${{ matrix.node-version }}
      #  uses: actions/setup-node@v2
      #  with:
      #    node-version: ${{ matrix.node-version }}

      - name: Load .env file
        env:
          DEV_ENV_FILE_CONTENTS: ${{ secrets.DEV_ENV_FILE_CONTENTS}}
        run: |
          echo "${{ secrets.DEV_ENV_FILE_CONTENTS}}" > .env
          cat .env
          source .env


      - name: Verify environment variables
        run: |
          echo "UI_URL is: $UI_URL"
          echo "API_URL is: $API_URL"
          env
